server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: murshid-backend

logging:
  level:
    root: INFO

supabase:
  url: ${SUPABASE_PROJECT_URL:}

frontend:
  origin: ${FRONTEND_ORIGIN:http://localhost:5173}

